"""Workflow-Control v1 persistence: SQLite run-store and durable object stores.

This package is the persistence boundary for Workflow-Control v1. It contains
the SQLite single-writer run-store substrate plus content-addressed Workflow
Blobs and Candidates and a controller-only Secret Store. SQLite may reference
objects only after the object stores have made the exact bytes durable. Redis
is never authority for these bytes, and secret values never enter SQLite,
Redis, logs, or ordinary API bodies.

See ``docs/wiki/architecture.md`` and ``docs/wiki/persistence-and-recovery.md``.
"""

from orcest.workflow_store.store import (
    DEFAULT_REDUCER_VERSION,
    PRIOR_STATE_NONE,
    SCHEMA_VERSION,
    SUPPORTED_REDUCER_VERSIONS,
    ActivityRecord,
    ActivityReviewAssignmentInput,
    ActivityReviewAssignmentRecord,
    AdmissionResult,
    ArtifactObjectRecord,
    AttemptClaimRecord,
    AttemptClaimReplayMaterialization,
    AttemptOfferInput,
    AttemptRecord,
    AttemptUnknownError,
    BudgetReportResult,
    CandidateDownloadRecord,
    CandidateRecord,
    CandidateUploadRecord,
    CapabilityKeyOperationResult,
    CapabilityKeyRegistryProjection,
    CapabilitySigningKey,
    CapacityReportEntryInput,
    CapacityReportResult,
    CasMismatchError,
    ControllerGatePermissions,
    ControllerModeOperationResult,
    ControllerModeProjection,
    ControllerOperationFactRecord,
    CredentialRotationReceiptRecord,
    DurableOperation,
    FaultInjectionPoint,
    ForgeInstanceRecord,
    ForgeObservationInput,
    ForgeObservationRecord,
    ForgeObservationRequestCompletion,
    ForgeObservationRequestRecord,
    ForgeObservationScheduleRecord,
    ForgeRequestFailureFactRecord,
    HealthObservationRecord,
    IdempotencyConflictError,
    ImmutableFact,
    IssuedCapabilityBinding,
    LaunchAcceptedReplay,
    LaunchAttestationRecord,
    MaintenanceMode,
    OfferGateEvaluation,
    OutboxRecord,
    PolicyUpdateRecord,
    ProjectionOutboxRecord,
    ProjectRecord,
    ProjectRegistrationOperationResult,
    ReducerVersionError,
    RunRecord,
    RunStore,
    RunStoreError,
    SchemaVersionError,
    SecretCurrentVersionProjection,
    SecretProvisionCheckpointRecord,
    SecretProvisionOperationResult,
    SecretVersionRecord,
    SnapshotGenerationRecord,
    SourceUniqueRecord,
    StartupIntegrityError,
    TransactionFault,
    Transition,
    WorkerLossReportResult,
    WorkflowBlobSqlRecord,
    WorkflowGateClosedError,
    WorkItemSnapshotRecord,
    WriterLockError,
    open_read_only,
)
from orcest.workflow_store.v1.blobs import WorkflowBlobRecord, WorkflowBlobStore
from orcest.workflow_store.v1.candidates import CandidateObjectRecord, CandidateObjectStore
from orcest.workflow_store.v1.errors import (
    DurableStoreError,
    IntegrityConflictError,
    LayoutError,
    ObjectNotFoundError,
    QuotaExceededError,
    StorageLockError,
)
from orcest.workflow_store.v1.fs import ControlLayout, QuotaConfig, StorageLock
from orcest.workflow_store.v1.offer_projection import (
    activity_offer_protocol,
    dispatch_pending_offers,
    offer_stream_key,
    reconstruct_open_offers,
)
from orcest.workflow_store.v1.secret_provision import (
    SecretProvisionReplayConflictError,
    provision_or_adopt_secret,
    reconcile_pending_secret_provision_operation,
)
from orcest.workflow_store.v1.secrets import (
    SecretReference,
    SecretStagingHandle,
    SecretStore,
    SecretVersionHandle,
)

__all__ = [
    "DEFAULT_REDUCER_VERSION",
    "PRIOR_STATE_NONE",
    "SCHEMA_VERSION",
    "SUPPORTED_REDUCER_VERSIONS",
    "ActivityRecord",
    "ActivityReviewAssignmentInput",
    "ActivityReviewAssignmentRecord",
    "AdmissionResult",
    "AttemptClaimRecord",
    "AttemptClaimReplayMaterialization",
    "AttemptOfferInput",
    "AttemptRecord",
    "ArtifactObjectRecord",
    "AttemptUnknownError",
    "BudgetReportResult",
    "activity_offer_protocol",
    "dispatch_pending_offers",
    "offer_stream_key",
    "reconstruct_open_offers",
    "CasMismatchError",
    "CapabilityKeyOperationResult",
    "CapabilityKeyRegistryProjection",
    "CapabilitySigningKey",
    "CapacityReportEntryInput",
    "CapacityReportResult",
    "ControllerGatePermissions",
    "ControllerModeOperationResult",
    "ControllerModeProjection",
    "ControllerOperationFactRecord",
    "DurableOperation",
    "FaultInjectionPoint",
    "ForgeInstanceRecord",
    "ForgeObservationInput",
    "ForgeObservationRecord",
    "ForgeObservationRequestCompletion",
    "ForgeObservationRequestRecord",
    "ForgeObservationScheduleRecord",
    "ForgeRequestFailureFactRecord",
    "HealthObservationRecord",
    "IdempotencyConflictError",
    "ImmutableFact",
    "IssuedCapabilityBinding",
    "LaunchAcceptedReplay",
    "LaunchAttestationRecord",
    "MaintenanceMode",
    "OfferGateEvaluation",
    "OutboxRecord",
    "ProjectRecord",
    "ProjectRegistrationOperationResult",
    "ProjectionOutboxRecord",
    "ReducerVersionError",
    "RunRecord",
    "RunStore",
    "RunStoreError",
    "SchemaVersionError",
    "SourceUniqueRecord",
    "StartupIntegrityError",
    "Transition",
    "WorkerLossReportResult",
    "WorkItemSnapshotRecord",
    "WorkflowBlobSqlRecord",
    "PolicyUpdateRecord",
    "SnapshotGenerationRecord",
    "TransactionFault",
    "WriterLockError",
    "WorkflowGateClosedError",
    "open_read_only",
    "WorkflowBlobRecord",
    "WorkflowBlobStore",
    "CandidateObjectRecord",
    "CandidateObjectStore",
    "CandidateDownloadRecord",
    "CandidateRecord",
    "CandidateUploadRecord",
    "DurableStoreError",
    "IntegrityConflictError",
    "LayoutError",
    "ObjectNotFoundError",
    "QuotaExceededError",
    "StorageLockError",
    "ControlLayout",
    "QuotaConfig",
    "StorageLock",
    "SecretReference",
    "SecretStagingHandle",
    "SecretStore",
    "SecretVersionHandle",
    "CredentialRotationReceiptRecord",
    "SecretCurrentVersionProjection",
    "SecretProvisionCheckpointRecord",
    "SecretProvisionOperationResult",
    "SecretVersionRecord",
    "SecretProvisionReplayConflictError",
    "provision_or_adopt_secret",
    "reconcile_pending_secret_provision_operation",
]
